default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: abid
  password: password
  host: mysql  # Use Docker service name as the host

development:
  <<: *default
  database: user_portal_development

test:
  <<: *default
  database: user_portal_test

production:
  <<: *default
  database: user_portal_production
